### ISSUE TITLE
Switching from VGA to framebuffer

### ISSUE THREAD

**Issue by 8dcc** [Dashbloxx/asterisk#1]
Hello, first of all, great job with the project.

I was having a hard time reading the code on the original `soso` repo, so I thought you might be able to help me (since the original repo doesn't have an "Issues" tab, and you have worked on the project). When booting the `soso` ISO from the releases page, it boots into (what appears to be) a VGA console. Then it switches into the framebuffer window manager. If you close all windows, it also returns to the old VGA console.

I have been working in my own OS for the past year, and although I am able to use both the VGA terminal and my own framebuffer terminal using the address returned by the bootloader, I can't figure out how to boot into the VGA console and switch back and forth between VGA and framebuffer.

I tried your fork following the steps on [BUILDING.md](https://github.com/Dashbloxx/asterisk/blob/3820f699e522c619ba8cf8e109f77d6ff4442103/docs/BUILDING.md), and I only see the VGA console being used. I don't know if this is simply because you haven't added that from the original repo yet, or if I am missing something.

Thanks in advance.

**Comment by Dashbloxx** [comment]
Well, the release only has the framebuffer working, because GRUB sets it up. The bootloader is what **usually** sets up the framebuffer. Usually the bootloader switches the video mode when it's at real mode, and then jumps to protected mode.
Also, when running the release, it's always at video mode after the kernel is loaded. It may appear as VGA text mode when the white and black terminal shows up, but this is actually a terminal that looks identical to the original VGA text mode, **which is actually running on top of the framebuffer**.

**Comment by Dashbloxx** [comment]
By the way, building when following the `BUILDING.md` file will just give you the kernel and initial RAMDisk, and it won't create a CDROM, which would be packaged with GRUB. QEMU in this case loads the kernel for us, but I haven't successfully gotten QEMU to switch to a framebuffer mode for Asterisk. Therefore, it stays at the **actual** VGA text mode.

**Comment by 8dcc** [comment]
> [...] but this is actually a terminal that looks identical to the original VGA text mode, **which is actually running on top of the framebuffer**.

Okay, so it's just a VGA-like framebuffer console as I thought, then.

> [...] QEMU in this case loads the kernel for us, but I haven't successfully gotten QEMU to switch to a framebuffer mode for Asterisk. Therefore, it stays at the **actual** VGA text mode.

This also happens in my OS. I have to build the ISO with the bootloader (in my case [limine](https://github.com/limine-bootloader/limine) but should not matter as I am using multiboot as well) and then use the multiboot header to request GFX mode.

If you want more information, you can have a look at my wiki ([multiboot header](https://github.com/fs-os/fs-os/wiki/Kernel-and-bootloader#multiboot-header), [entry point](https://github.com/fs-os/fs-os/wiki/Kernel-and-bootloader#entry-point)) and my Makefile ([ISO target](https://github.com/fs-os/fs-os/blob/a80bf4ce02ab95546e837b472df570889a45b58d/Makefile#L75-L87), [qemu command](https://github.com/fs-os/fs-os/blob/a80bf4ce02ab95546e837b472df570889a45b58d/Makefile#L11-L22)).

Closing the issue, since you answered my original question.
